#!/bin/sh
set -x

rm -rf build
mkdir build
sh makefile.sh > build/Makefile.am
cp configure.ac build/
cp makefile.sh build/
cd build
mkdir m4;

aclocal -I m4
autoheader
libtoolize --force
automake --add-missing
autoconf

./configure --prefix=`pwd` CXXFLAGS=
if [ $? -ne 0 ];then
    exit -1;
fi;

make clean;
make -j4 all;
make install