#!/bin/sh
set -x

rm -rf build
mkdir build
mkdir -p lib
cp configure.ac build/
sh makefile.sh > build/Makefile.am

cd build
mkdir -p m4;

aclocal -I m4
autoheader
libtoolize --force
automake --add-missing
autoconf

./configure --prefix=`pwd`
if [ $? -ne 0 ];then
    exit -1;
fi;

make clean;
make -j4 all;
make install